[features]
seeds = false
[programs.devnet]
nolosslottery = "4EhDYPWxypecvZV4v9FbaExoAUmiR38sCUHX4BQYhW4W"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
