[features]
seeds = false
[programs.devnet]
nolosslottery = "ACqyU5JmS1a7qWTCP9ckoG7A1GXFofS52nuoiq7bq4JF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
