[features]
seeds = false
[programs.devnet]
nolosslottery = "GQrLSMRsrDE7rR9zEZkctPiZdpfFGcttrUr92LyWN3sr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
